project_id = "mczqwqsvumfsneoknlep"

[functions.pesapal-withdraw-ipn]
verify_jwt = false

[functions.paymentology-accept-payment]
verify_jwt = false

[functions.paymentology-issue-card]
verify_jwt = true

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.hook.send_email]
enabled = false
uri = "https://mczqwqsvumfsneoknlep.supabase.co/functions/v1/send-auth-email"

[functions.send-auth-email]
verify_jwt = false

[functions.get-exchange-rate]
verify_jwt = false

[functions.pesapal-submit-order]
verify_jwt = false

[functions.pesapal-ipn]
verify_jwt = false

[functions.pesapal-register-ipn]
verify_jwt = true

[functions.setup-test-configs]
verify_jwt = true

[functions.send-payment-emails]
verify_jwt = false

[functions.pesapal-check-status]
verify_jwt = true

[functions.manage-payment-configs]
verify_jwt = true

[functions.mtn-momo-withdraw]
verify_jwt = true

[functions.pesapal-withdraw]
verify_jwt = true